spring.application.name=racebets
JWT_SECRET=UitSYSYuN3paXgPjJeRnF2dihPPXx2c3BdQWB0VSZmXCktSwPCt8dmN7RU5FamApMGp0TnkS2FBQ2R9PzJJJ0Ngdkc6cGtNI0FSVDd0IA
jwt.expiration=3600000
spring.jpa.open-in-view=false
racebets.dev-admin.enabled=false
