spring.application.name=racebets
jwt.expiration=3600000
spring.jpa.open-in-view=false
racebets.dev-admin.enabled=false
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=3MB
