CREATE TABLE app_feature_settings (
    id BIGINT NOT NULL,
    betting_enabled BOOLEAN NOT NULL,
    quiz_enabled BOOLEAN NOT NULL,
    CONSTRAINT pk_app_feature_settings PRIMARY KEY (id)
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    birth_date DATE,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_present BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE horses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_horses PRIMARY KEY (id)
);

CREATE TABLE races (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    race_img_url VARCHAR(500),
    state VARCHAR(255) NOT NULL,
    visible_on_live BOOLEAN NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_races PRIMARY KEY (id)
);

CREATE TABLE race_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    race_id BIGINT NOT NULL,
    horse_id BIGINT NOT NULL,
    horse_number INTEGER NOT NULL,
    rank INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_race_entries PRIMARY KEY (id),
    CONSTRAINT uk_race_entries_race_horse UNIQUE (race_id, horse_id),
    CONSTRAINT uk_race_entries_race_number UNIQUE (race_id, horse_number),
    CONSTRAINT fk_race_entries_race FOREIGN KEY (race_id) REFERENCES races (id),
    CONSTRAINT fk_race_entries_horse FOREIGN KEY (horse_id) REFERENCES horses (id)
);

CREATE TABLE bets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    race_entry_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    date_time_bet TIMESTAMP WITH TIME ZONE NOT NULL,
    state VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_bets PRIMARY KEY (id),
    CONSTRAINT fk_bets_race_entry FOREIGN KEY (race_entry_id) REFERENCES race_entries (id),
    CONSTRAINT fk_bets_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    logo_data OID NOT NULL,
    logo_content_type VARCHAR(40) NOT NULL,
    display_on_waiting BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_partners PRIMARY KEY (id)
);

CREATE TABLE quiz_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(140) NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_quiz_sets PRIMARY KEY (id)
);

CREATE TABLE quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quiz_set_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    text VARCHAR(500) NOT NULL,
    question_image_data_url OID,
    answer_image_data_url OID,
    duration_seconds INTEGER NOT NULL,
    CONSTRAINT pk_quiz_questions PRIMARY KEY (id),
    CONSTRAINT fk_quiz_questions_set FOREIGN KEY (quiz_set_id) REFERENCES quiz_sets (id) ON DELETE CASCADE
);

CREATE TABLE quiz_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    text VARCHAR(240) NOT NULL,
    correct BOOLEAN NOT NULL,
    CONSTRAINT pk_quiz_answers PRIMARY KEY (id),
    CONSTRAINT fk_quiz_answers_question FOREIGN KEY (question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE
);

CREATE TABLE quiz_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    quiz_set_id BIGINT NOT NULL,
    phase VARCHAR(40) NOT NULL,
    current_question_index INTEGER NOT NULL,
    phase_started_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_quiz_sessions PRIMARY KEY (id),
    CONSTRAINT fk_quiz_sessions_set FOREIGN KEY (quiz_set_id) REFERENCES quiz_sets (id)
);

CREATE TABLE quiz_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_quiz_participants PRIMARY KEY (id),
    CONSTRAINT uk_quiz_participants_session_user UNIQUE (session_id, user_id),
    CONSTRAINT fk_quiz_participants_session FOREIGN KEY (session_id) REFERENCES quiz_sessions (id),
    CONSTRAINT fk_quiz_participants_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE quiz_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    correct BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_quiz_submissions PRIMARY KEY (id),
    CONSTRAINT uk_quiz_submissions_session_question_user UNIQUE (session_id, question_id, user_id),
    CONSTRAINT fk_quiz_submissions_session FOREIGN KEY (session_id) REFERENCES quiz_sessions (id),
    CONSTRAINT fk_quiz_submissions_question FOREIGN KEY (question_id) REFERENCES quiz_questions (id),
    CONSTRAINT fk_quiz_submissions_answer FOREIGN KEY (answer_id) REFERENCES quiz_answers (id),
    CONSTRAINT fk_quiz_submissions_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX idx_bets_race_entry ON bets (race_entry_id);
CREATE INDEX idx_bets_user ON bets (user_id);
CREATE INDEX idx_race_entries_horse ON race_entries (horse_id);
CREATE INDEX idx_quiz_questions_set ON quiz_questions (quiz_set_id);
CREATE INDEX idx_quiz_answers_question ON quiz_answers (question_id);
CREATE INDEX idx_quiz_sessions_set ON quiz_sessions (quiz_set_id);
CREATE INDEX idx_quiz_participants_user ON quiz_participants (user_id);
CREATE INDEX idx_quiz_submissions_question ON quiz_submissions (question_id);
CREATE INDEX idx_quiz_submissions_answer ON quiz_submissions (answer_id);
CREATE INDEX idx_quiz_submissions_user ON quiz_submissions (user_id);

INSERT INTO app_feature_settings (id, betting_enabled, quiz_enabled)
VALUES (1, TRUE, TRUE);
