ALTER TABLE app_user ALTER COLUMN password_hash DROP NOT NULL;

CREATE TABLE oauth_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    email_at_link VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_oauth_identity PRIMARY KEY (id),
    CONSTRAINT fk_oauth_identity_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_oauth_identity_issuer_subject UNIQUE (issuer, subject)
);

CREATE TABLE oauth_login_code (
    code_hash VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    pending_issuer VARCHAR(255),
    pending_subject VARCHAR(255),
    pending_email VARCHAR(255),
    CONSTRAINT pk_oauth_login_code PRIMARY KEY (code_hash),
    CONSTRAINT fk_oauth_login_code_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_oauth_identity_user ON oauth_identity (user_id);
CREATE INDEX idx_oauth_login_code_expiry ON oauth_login_code (expires_at);
