ALTER TABLE quiz_sessions
    ADD COLUMN IF NOT EXISTS active_slot BOOLEAN;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'quiz_sessions'::regclass
          AND conname = 'uk_quiz_sessions_active_slot'
    ) THEN
        IF EXISTS (
            SELECT active_slot
            FROM quiz_sessions
            WHERE active_slot IS NOT NULL
            GROUP BY active_slot
            HAVING COUNT(*) > 1
        ) THEN
            RAISE WARNING 'Preserving duplicate quiz_sessions.active_slot values; unique constraint was not created';
        ELSE
            ALTER TABLE quiz_sessions
                ADD CONSTRAINT uk_quiz_sessions_active_slot UNIQUE (active_slot);
        END IF;
    END IF;
END
$$;

ALTER TABLE app_user
    ALTER COLUMN password_hash DROP NOT NULL;

CREATE TABLE IF NOT EXISTS oauth_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    email_at_link VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_oauth_identity PRIMARY KEY (id),
    CONSTRAINT fk_oauth_identity_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_oauth_identity_issuer_subject UNIQUE (issuer, subject)
);

CREATE TABLE IF NOT EXISTS oauth_login_code (
    code_hash VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    pending_issuer VARCHAR(255),
    pending_subject VARCHAR(255),
    pending_email VARCHAR(255),
    CONSTRAINT pk_oauth_login_code PRIMARY KEY (code_hash),
    CONSTRAINT fk_oauth_login_code_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_oauth_identity_user ON oauth_identity (user_id);
CREATE INDEX IF NOT EXISTS idx_oauth_login_code_expiry ON oauth_login_code (expires_at);

ALTER TABLE app_user
    ADD COLUMN IF NOT EXISTS tutorial_completed BOOLEAN NOT NULL DEFAULT FALSE;
