ALTER TABLE app_feature_settings ADD COLUMN active_mode VARCHAR(40);

UPDATE app_feature_settings
SET active_mode = CASE WHEN betting_enabled = TRUE THEN 'BETTING' ELSE 'QUIZ' END;

ALTER TABLE app_feature_settings ALTER COLUMN active_mode SET NOT NULL;
ALTER TABLE app_feature_settings DROP COLUMN betting_enabled;
ALTER TABLE app_feature_settings DROP COLUMN quiz_enabled;

CREATE TABLE word_cloud_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(300) NOT NULL,
    status VARCHAR(40) NOT NULL,
    active_slot BOOLEAN,
    opened_at TIMESTAMP WITH TIME ZONE,
    revealed_at TIMESTAMP WITH TIME ZONE,
    closed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_word_cloud_questions PRIMARY KEY (id),
    CONSTRAINT uk_word_cloud_questions_active_slot UNIQUE (active_slot)
);

CREATE TABLE word_cloud_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    display_text VARCHAR(80) NOT NULL,
    normalized_text VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_word_cloud_responses PRIMARY KEY (id),
    CONSTRAINT uk_word_cloud_responses_question_user UNIQUE (question_id, user_id),
    CONSTRAINT fk_word_cloud_responses_question FOREIGN KEY (question_id) REFERENCES word_cloud_questions (id) ON DELETE CASCADE,
    CONSTRAINT fk_word_cloud_responses_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_word_cloud_questions_status ON word_cloud_questions (status);
CREATE INDEX idx_word_cloud_responses_question ON word_cloud_responses (question_id);
CREATE INDEX idx_word_cloud_responses_user ON word_cloud_responses (user_id);
