CREATE TABLE word_cloud_moderated_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT NOT NULL,
    normalized_text VARCHAR(80) NOT NULL,
    CONSTRAINT pk_word_cloud_moderated_words PRIMARY KEY (id),
    CONSTRAINT uk_word_cloud_moderated_words_question_text UNIQUE (question_id, normalized_text),
    CONSTRAINT fk_word_cloud_moderated_words_question FOREIGN KEY (question_id) REFERENCES word_cloud_questions (id) ON DELETE CASCADE
);

CREATE INDEX idx_word_cloud_moderated_words_question ON word_cloud_moderated_words (question_id);
